export type Category = 'analysis' | 'writing' | 'client' | 'research' | 'strategy' | 'data' | 'email' | 'comms' | 'finance' | 'marketing' | 'operations' | 'legal' | 'customer'

export interface Prompt {
  id: number
  title: string
  body: string
  category: Category
  uses: number
  isPro: boolean
  pack: 'analyst' | 'smallbiz'
}

export const CAT_COLORS: Record<Category, { dot: string; label: string }> = {
  analysis:   { dot: '#2a6b4a', label: '#2a6b4a' },
  writing:    { dot: '#2a4a8a', label: '#2a4a8a' },
  client:     { dot: '#c0522a', label: '#c0522a' },
  research:   { dot: '#8a6020', label: '#8a6020' },
  strategy:   { dot: '#2a6a8a', label: '#2a6a8a' },
  data:       { dot: '#6a2a6a', label: '#6a2a6a' },
  email:      { dot: '#5a2a8a', label: '#5a2a8a' },
  comms:      { dot: '#2a5a3a', label: '#2a5a3a' },
  finance:    { dot: '#2d7a2d', label: '#2d7a2d' },
  marketing:  { dot: '#7a2d5a', label: '#7a2d5a' },
  operations: { dot: '#2d5a7a', label: '#2d5a7a' },
  legal:      { dot: '#7a5a2d', label: '#7a5a2d' },
  customer:   { dot: '#5a2d7a', label: '#5a2d7a' },
}

export const ANALYST_PROMPTS: Prompt[] = [
  { id:1,  pack:'analyst', category:'analysis', isPro:false, uses:89,  title:'Issue tree breakdown',        body:'Build a MECE issue tree for the following problem: [problem statement]. Industry: [industry]. Decompose into root causes (top-down MECE), hypotheses for each, and the 2–3 most important to investigate first. Output as a structured outline.' },
  { id:2,  pack:'analyst', category:'analysis', isPro:false, uses:64,  title:'Root cause analysis',          body:'Conduct a root cause analysis for [problem] at [company or context]. Use the 5-Whys method. For each why, provide evidence needed to confirm. End with: top cause, confidence level, and recommended first action.' },
  { id:3,  pack:'analyst', category:'analysis', isPro:false, uses:71,  title:'SWOT synthesis',               body:'Create a strategic SWOT analysis for [company] in [industry]. Strengths and weaknesses should be internal and specific. Opportunities and threats should reference current market conditions. End with 3 strategic implications.' },
  { id:4,  pack:'analyst', category:'analysis', isPro:true,  uses:43,  title:'Hypothesis stress-test',       body:'I have the following hypothesis: [hypothesis]. Play devil\'s advocate. What are the 3 strongest arguments against it? What data would disprove it? What assumptions is it relying on? Rate the hypothesis robustness 1–10.' },
  { id:5,  pack:'analyst', category:'analysis', isPro:true,  uses:38,  title:'Scenario planning matrix',     body:'Build a 2x2 scenario matrix for [organization] planning around [key uncertainty 1] and [key uncertainty 2]. Name each quadrant, describe it in 3 sentences, and identify the top strategic priority in each.' },
  { id:6,  pack:'analyst', category:'analysis', isPro:true,  uses:29,  title:'Logic check reviewer',         body:'Review the following argument for logical errors, unsupported assumptions, and gaps in reasoning: [argument or text]. Flag each issue with: (1) what the flaw is, (2) why it matters, (3) how to fix it.' },
  { id:7,  pack:'analyst', category:'writing',  isPro:false, uses:112, title:'Executive summary writer',     body:'Write a concise executive summary for [client name] in the [industry] sector. The document covers [topic]. Audience: [audience]. Tone: professional and direct. Length: 200–250 words. Open with the key finding, supporting points, then a clear recommendation.' },
  { id:8,  pack:'analyst', category:'writing',  isPro:false, uses:87,  title:'Data findings narrative',      body:'Convert the following data findings into a clear narrative for a non-technical audience. Data: [paste findings]. Format: 1) What we found, 2) Why it matters, 3) What we recommend. Avoid jargon. Use plain language throughout.' },
  { id:9,  pack:'analyst', category:'writing',  isPro:false, uses:55,  title:'Slide talking points',         body:'Write speaker notes for a [number]-slide presentation on [topic] for [audience]. Each note: 3–4 sentences, conversational, adds context not visible on the slide. Do not repeat slide text verbatim.' },
  { id:10, pack:'analyst', category:'writing',  isPro:true,  uses:48,  title:'Report section drafter',       body:'Draft the [section name] section of a report on [topic] for [client or audience]. Length: [target length]. Tone: [tone]. Include: [key points to cover]. Use headers and short paragraphs. Avoid passive voice.' },
  { id:11, pack:'analyst', category:'writing',  isPro:true,  uses:61,  title:'Abstract / TL;DR generator',  body:'Read the following document and write a 3-sentence TL;DR followed by a 150-word abstract. The TL;DR should be conversational. The abstract should be formal and citation-ready. Document: [paste document]' },
  { id:12, pack:'analyst', category:'client',   isPro:false, uses:94,  title:'Meeting prep brief',           body:'I have a meeting with [client name] at [company] on [date]. Topic: [topic]. Prepare: 1) Three smart questions to ask, 2) Key points to cover, 3) Potential objections and responses, 4) What a great outcome looks like.' },
  { id:13, pack:'analyst', category:'client',   isPro:false, uses:52,  title:'Stakeholder map builder',      body:'Build a stakeholder map for [project] at [organization]. For each stakeholder group: role, level of influence (high/med/low), stance toward [initiative] (support/neutral/resist), and recommended engagement approach.' },
  { id:14, pack:'analyst', category:'client',   isPro:true,  uses:45,  title:'Feedback synthesizer',         body:'Synthesize the following client feedback into themes: [paste feedback]. Group by: 1) What\'s working, 2) Pain points, 3) Requests and wishes. Highlight the 2–3 most urgent themes. Suggest one quick win.' },
  { id:15, pack:'analyst', category:'client',   isPro:true,  uses:67,  title:'Recommendation memo',          body:'Write a concise recommendation memo for [client] recommending [action]. Format: Situation, Complication, Question, Answer (SCQA). Length: 300 words. End with: decision required, deadline, and owner.' },
  { id:16, pack:'analyst', category:'client',   isPro:true,  uses:39,  title:'Objection handler',            body:'I expect the following objection from [client or stakeholder]: "[objection]". Prepare: 1) The strongest version of their concern, 2) A respectful response, 3) Reframe toward [goal], 4) Bridging question to move forward.' },
  { id:17, pack:'analyst', category:'research', isPro:false, uses:73,  title:'Competitor landscape',         body:'Summarize the competitive landscape for [company or product] in the [industry] market. Cover: key players, positioning, pricing if known, strengths and weaknesses, and one whitespace opportunity. Under 400 words.' },
  { id:18, pack:'analyst', category:'research', isPro:false, uses:41,  title:'Literature synthesis',         body:'Review the following sources on [topic] and produce a structured summary: [paste sources]. Format: 1) Main themes, 2) Points of agreement, 3) Contradictions or gaps, 4) Most important insight for [use case].' },
  { id:19, pack:'analyst', category:'research', isPro:true,  uses:36,  title:'Expert interview guide',       body:'Create an interview guide for a 45-minute conversation with a [role] at [type of organization] about [topic]. Include: 5 open-ended questions, 3 follow-up probes per question, and one closing question about future trends.' },
  { id:20, pack:'analyst', category:'research', isPro:true,  uses:28,  title:'Market sizing approach',       body:'Outline a market sizing approach for [market]. Use both top-down (TAM/SAM/SOM) and bottom-up methods. State key assumptions for each. Identify the 2–3 variables that most affect the estimate.' },
  { id:21, pack:'analyst', category:'strategy', isPro:false, uses:56,  title:'Strategic options generator',  body:'Generate 4–5 distinct strategic options for [organization] facing [challenge]. For each: name it, describe it in 2 sentences, list the main risk, and rate it on feasibility (1–5) and impact (1–5).' },
  { id:22, pack:'analyst', category:'strategy', isPro:true,  uses:49,  title:'Prioritization framework',     body:'Help me prioritize the following initiatives: [list initiatives]. Evaluate each on: strategic fit, effort required, speed to value, and risk. Output as a 2x2 priority matrix (impact vs. effort) with recommended sequence.' },
  { id:23, pack:'analyst', category:'strategy', isPro:true,  uses:44,  title:'OKR drafter',                  body:'Draft OKRs for [team or department] for [time period]. Objective: [objective]. Write 3–4 measurable key results. Each KR should be specific, time-bound, ambitious but achievable, and clearly owned.' },
  { id:24, pack:'analyst', category:'strategy', isPro:true,  uses:62,  title:'Business case builder',        body:'Build a concise business case for [initiative] at [organization]. Cover: problem statement, proposed solution, costs, expected benefits, risks, and recommended next steps. Audience: [decision-maker]. Length: 400 words.' },
  { id:25, pack:'analyst', category:'data',     isPro:false, uses:47,  title:'Dashboard KPI brief',          body:'Define the key metrics for a dashboard tracking [business goal] at [type of organization]. For each metric: name, definition, data source, target, and why it matters. Include one leading and one lagging indicator.' },
  { id:26, pack:'analyst', category:'data',     isPro:false, uses:38,  title:'Data story builder',           body:'I have data showing [finding]. Help me build a data story for [audience]. Structure: 1) The setup (context), 2) The tension (what the data reveals), 3) The resolution (recommended action). Use one analogy.' },
  { id:27, pack:'analyst', category:'data',     isPro:true,  uses:29,  title:'Anomaly explainer',            body:'I observed the following anomaly in my data: [describe anomaly]. Generate 5 hypotheses ranging from mundane (data error) to significant (real business change). Rate each likelihood 1–5 and suggest first investigation steps.' },
  { id:28, pack:'analyst', category:'data',     isPro:true,  uses:22,  title:'Survey design assistant',      body:'Design a survey to measure [what you want to measure] among [target respondents]. Include: 8–10 questions mixing Likert scale, multiple choice, and one open-ended. Avoid leading questions. Include a screening question.' },
  { id:29, pack:'analyst', category:'email',    isPro:false, uses:103, title:'Post-meeting follow-up',       body:'Write a professional follow-up email after a meeting with [client name] at [company]. Points discussed: [points]. Next steps agreed: [next steps]. Tone: warm but concise. End with a clear call to action and deadline.' },
  { id:30, pack:'analyst', category:'email',    isPro:false, uses:58,  title:'Difficult message drafter',    body:'Help me write [email type] to [recipient] about [situation]. Tone: [tone]. Goals: be honest, maintain the relationship, and suggest a clear path forward.' },
  { id:31, pack:'analyst', category:'comms',    isPro:true,  uses:34,  title:'Announcement writer',          body:'Write an internal announcement for [organization] about [change or initiative]. Audience: [audience]. Cover: what\'s changing, why, timeline, what people need to do, and who to contact. Tone: [tone].' },
  { id:32, pack:'analyst', category:'comms',    isPro:true,  uses:41,  title:'Talking points builder',       body:'Build talking points for [speaker] to address [topic] with [audience]. Format: 3–5 main points, each with: one sentence summary, 2 supporting facts or examples, and a transition to the next point.' },
]

export const SMALLBIZ_PROMPTS: Prompt[] = [
  { id:101, pack:'smallbiz', category:'finance',    isPro:false, uses:0, title:'Profit & loss summary',          body:'Summarize the following profit and loss data for [business name] for [time period]: [paste data]. Format as: total revenue, total expenses broken down by category, net profit or loss, profit margin percentage, and one key insight about the biggest cost driver.' },
  { id:102, pack:'smallbiz', category:'finance',    isPro:false, uses:0, title:'Cash flow forecast',              body:'Create a simple cash flow forecast for [business name] for the next [number] months. Expected monthly revenue: [revenue]. Fixed monthly costs: [fixed costs]. Variable costs: [variable costs]. Flag any months where cash flow may go negative and suggest one action to prevent it.' },
  { id:103, pack:'smallbiz', category:'finance',    isPro:false, uses:0, title:'Tax prep checklist',              body:'Generate a tax preparation checklist for a [business type] business with [number] employees operating in [state or country]. Include: documents to gather, deadlines, common deductions for this business type, and questions to ask my accountant.' },
  { id:104, pack:'smallbiz', category:'finance',    isPro:true,  uses:0, title:'Pricing calculator prompt',       body:'Help me price [product or service]. My costs are: [costs]. Competitors charge: [competitor pricing]. My target margin is [margin]%. Suggest 3 pricing options (budget, standard, premium) with rationale for each and which I should lead with.' },
  { id:105, pack:'smallbiz', category:'finance',    isPro:false, uses:0, title:'Invoice follow-up email',         body:'Write a professional but firm follow-up email to [client name] whose invoice of [amount] for [service] is [number] days overdue. Tone: polite but clear. Include: original due date, payment options, and a specific deadline to respond by.' },
  { id:106, pack:'smallbiz', category:'marketing',  isPro:false, uses:0, title:'Social media content calendar',  body:'Create a 2-week social media content calendar for [business name], a [business type] targeting [target audience]. Platforms: [platforms]. Include: post topic, format (image/video/text), caption hook, and best posting time. Mix promotional and educational content 80/20.' },
  { id:107, pack:'smallbiz', category:'marketing',  isPro:false, uses:0, title:'Google Business profile',        body:'Write a compelling Google Business profile description for [business name], a [business type] located in [location]. Highlight: [key services or products], [unique selling point], and include a call to action. Keep it under 750 characters.' },
  { id:108, pack:'smallbiz', category:'marketing',  isPro:false, uses:0, title:'Email newsletter draft',         body:'Write a monthly email newsletter for [business name] covering: [topic 1], [topic 2], and [promotion or offer]. Tone: [tone]. Audience: [audience]. Include a subject line, preview text, 3 short sections with headers, and a clear call to action button.' },
  { id:109, pack:'smallbiz', category:'marketing',  isPro:false, uses:0, title:'Customer review response',       body:'Write a professional response to the following [positive or negative] customer review for [business name]: "[paste review]". For negative reviews: acknowledge the issue, apologize sincerely, offer a resolution. For positive: thank them warmly and reinforce what they loved.' },
  { id:110, pack:'smallbiz', category:'marketing',  isPro:true,  uses:0, title:'Ad copy writer',                 body:'Write 3 variations of ad copy for [business name] promoting [product or service] to [target audience]. Platform: [platform]. Each variation should have: a headline under 40 characters, body copy under 125 characters, and a call to action.' },
  { id:111, pack:'smallbiz', category:'operations', isPro:false, uses:0, title:'Standard operating procedure',   body:'Write a standard operating procedure (SOP) for [task or process] at [business name]. Include: purpose, who is responsible, step-by-step instructions, tools or materials needed, quality checks, and what to do if something goes wrong.' },
  { id:112, pack:'smallbiz', category:'operations', isPro:false, uses:0, title:'Job description writer',         body:'Write a job description for a [job title] position at [business name], a [business type]. Include: role summary, key responsibilities (6-8 bullet points), required qualifications, nice-to-have skills, compensation range [range], and 2-3 sentences about company culture.' },
  { id:113, pack:'smallbiz', category:'operations', isPro:true,  uses:0, title:'Vendor comparison',              body:'Help me compare the following vendors for [product or service]: [vendor 1], [vendor 2], [vendor 3]. Evaluation criteria: price, quality, reliability, customer support, and contract terms. Output as a comparison table with a recommended choice and reasoning.' },
  { id:114, pack:'smallbiz', category:'operations', isPro:false, uses:0, title:'Meeting agenda builder',         body:'Create a structured agenda for a [duration] team meeting at [business name] on [topic]. Include: objectives, time allocations for each item, who leads each section, and a 5-minute slot for questions. Make it efficient — no filler.' },
  { id:115, pack:'smallbiz', category:'legal',      isPro:false, uses:0, title:'Contract plain English summary', body:'Summarize the key terms of the following contract in plain English for a small business owner: [paste contract text]. Cover: what I am agreeing to, payment terms, termination clauses, liability limits, and any red flags I should ask a lawyer about.' },
  { id:116, pack:'smallbiz', category:'legal',      isPro:true,  uses:0, title:'Privacy policy draft',           body:'Draft a simple privacy policy for [business name], a [business type] that collects [types of data]. Cover: what data is collected, how it is used, how it is stored, user rights, and contact information. Plain English only.' },
  { id:117, pack:'smallbiz', category:'legal',      isPro:false, uses:0, title:'Refund policy writer',           body:'Write a clear refund and return policy for [business name] selling [products or services]. Refund window: [number] days. Conditions: [conditions]. Tone: fair and customer-friendly. Include how to request a refund and expected processing time.' },
  { id:118, pack:'smallbiz', category:'customer',   isPro:false, uses:0, title:'Customer complaint handler',     body:'A customer has complained about [issue] with [product or service]. Write a response that: acknowledges the frustration, takes responsibility where appropriate, explains what happened, offers [resolution], and thanks them for their feedback. Tone: empathetic and professional.' },
  { id:119, pack:'smallbiz', category:'customer',   isPro:false, uses:0, title:'FAQ page writer',                body:'Write an FAQ page for [business name] covering the [number] most common questions customers ask about [product or service]. For each question: write it from the customer\'s perspective, answer clearly in 2-4 sentences, and anticipate the follow-up concern.' },
  { id:120, pack:'smallbiz', category:'customer',   isPro:false, uses:0, title:'Onboarding welcome email',       body:'Write a welcome email for new customers of [business name] who just purchased [product or service]. Include: a warm welcome, what happens next (3 clear steps), how to get support, and one tip to get the most value immediately. Tone: [tone].' },
  { id:121, pack:'smallbiz', category:'strategy',   isPro:false, uses:0, title:'Business plan one-pager',        body:'Write a one-page business plan for [business name], a [business type]. Cover: problem we solve, our solution, target customer, revenue model, key costs, competitive advantage, and 90-day goals. Keep each section to 2-3 sentences. Audience: potential investor or bank.' },
  { id:122, pack:'smallbiz', category:'strategy',   isPro:false, uses:0, title:'SWOT for small business',        body:'Create a SWOT analysis for [business name], a [business type] in [location] serving [target market]. Be specific and actionable. End with: the single biggest opportunity to pursue in the next 90 days and the single biggest risk to mitigate.' },
  { id:123, pack:'smallbiz', category:'strategy',   isPro:true,  uses:0, title:'Competitor analysis',            body:'Analyze the competitive landscape for [business name] in the [industry] market in [location]. Competitors: [competitor 1], [competitor 2], [competitor 3]. For each: strengths, weaknesses, pricing, and customer reviews. Identify one gap we can exploit.' },
  { id:124, pack:'smallbiz', category:'strategy',   isPro:true,  uses:0, title:'90-day action plan',             body:'Create a 90-day action plan for [business name] to achieve [goal]. Break it into 3 monthly sprints with 3-5 specific actions each. For each action: who owns it, what success looks like, and estimated time required. Be realistic for a small team of [team size].' },
]

export const STARTER_PROMPTS: Prompt[] = [...ANALYST_PROMPTS, ...SMALLBIZ_PROMPTS]

export function extractVars(body: string): string[] {
  const matches = Array.from(body.matchAll(/\[([^\]]+)\]/g))
  return Array.from(new Set(matches.map(m => m[1])))
}
