export type Category = 'analysis' | 'writing' | 'client' | 'research' | 'strategy' | 'data' | 'email' | 'comms'

export interface Prompt {
  id: number
  title: string
  body: string
  category: Category
  uses: number
  isPro: boolean
}

export const STARTER_PROMPTS: Prompt[] = [
  { id:1, category:'analysis', isPro:false, uses:89, title:'Issue tree breakdown', body:'Build a MECE issue tree for the following problem: [problem statement]. Industry: [industry]. Decompose into root causes (top-down MECE), hypotheses for each, and the 2–3 most important to investigate first. Output as a structured outline.' },
  { id:2, category:'analysis', isPro:false, uses:64, title:'Root cause analysis', body:'Conduct a root cause analysis for [problem] at [company or context]. Use the 5-Whys method. For each why, provide evidence needed to confirm. End with: top cause, confidence level, and recommended first action.' },
  { id:3, category:'analysis', isPro:false, uses:71, title:'SWOT synthesis', body:'Create a strategic SWOT analysis for [company] in [industry]. Strengths and weaknesses should be internal and specific. Opportunities and threats should reference current market conditions. End with 3 strategic implications.' },
  { id:4, category:'analysis', isPro:true, uses:43, title:'Hypothesis stress-test', body:'I have the following hypothesis: [hypothesis]. Play devil\'s advocate. What are the 3 strongest arguments against it? What data would disprove it? What assumptions is it relying on? Rate the hypothesis robustness 1–10.' },
  { id:5, category:'analysis', isPro:true, uses:38, title:'Scenario planning matrix', body:'Build a 2x2 scenario matrix for [organization] planning around [key uncertainty 1] and [key uncertainty 2]. Name each quadrant, describe it in 3 sentences, and identify the top strategic priority in each.' },
  { id:6, category:'analysis', isPro:true, uses:29, title:'Logic check reviewer', body:'Review the following argument for logical errors, unsupported assumptions, and gaps in reasoning: [argument or text]. Flag each issue with: (1) what the flaw is, (2) why it matters, (3) how to fix it.' },
  { id:7, category:'writing', isPro:false, uses:112, title:'Executive summary writer', body:'Write a concise executive summary for [client name] in the [industry] sector. The document covers [topic]. Audience: [audience]. Tone: professional and direct. Length: 200–250 words. Open with the key finding, supporting points, then a clear recommendation.' },
  { id:8, category:'writing', isPro:false, uses:87, title:'Data findings narrative', body:'Convert the following data findings into a clear narrative for a non-technical audience. Data: [paste findings]. Format: 1) What we found, 2) Why it matters, 3) What we recommend. Avoid jargon. Use plain language throughout.' },
  { id:9, category:'writing', isPro:false, uses:55, title:'Slide talking points', body:'Write speaker notes for a [number]-slide presentation on [topic] for [audience]. Each note: 3–4 sentences, conversational, adds context not visible on the slide. Do not repeat slide text verbatim.' },
  { id:10, category:'writing', isPro:true, uses:48, title:'Report section drafter', body:'Draft the [section name] section of a report on [topic] for [client or audience]. Length: [target length]. Tone: [tone]. Include: [key points to cover]. Use headers and short paragraphs. Avoid passive voice.' },
  { id:11, category:'writing', isPro:true, uses:61, title:'Abstract / TL;DR generator', body:'Read the following document and write a 3-sentence TL;DR followed by a 150-word abstract. The TL;DR should be conversational. The abstract should be formal and citation-ready. Document: [paste document]' },
  { id:12, category:'client', isPro:false, uses:94, title:'Meeting prep brief', body:'I have a meeting with [client name] at [company] on [date]. Topic: [topic]. Prepare: 1) Three smart questions to ask, 2) Key points to cover, 3) Potential objections and responses, 4) What a great outcome looks like.' },
  { id:13, category:'client', isPro:false, uses:52, title:'Stakeholder map builder', body:'Build a stakeholder map for [project] at [organization]. For each stakeholder group: role, level of influence (high/med/low), stance toward [initiative] (support/neutral/resist), and recommended engagement approach.' },
  { id:14, category:'client', isPro:true, uses:45, title:'Feedback synthesizer', body:'Synthesize the following client feedback into themes: [paste feedback]. Group by: 1) What\'s working, 2) Pain points, 3) Requests and wishes. Highlight the 2–3 most urgent themes. Suggest one quick win.' },
  { id:15, category:'client', isPro:true, uses:67, title:'Recommendation memo', body:'Write a concise recommendation memo for [client] recommending [action]. Format: Situation, Complication, Question, Answer (SCQA). Length: 300 words. End with: decision required, deadline, and owner.' },
  { id:16, category:'client', isPro:true, uses:39, title:'Objection handler', body:'I expect the following objection from [client or stakeholder]: "[objection]". Prepare: 1) The strongest version of their concern, 2) A respectful response, 3) Reframe toward [goal], 4) Bridging question to move forward.' },
  { id:17, category:'research', isPro:false, uses:73, title:'Competitor landscape', body:'Summarize the competitive landscape for [company or product] in the [industry] market. Cover: key players, positioning, pricing if known, strengths and weaknesses, and one whitespace opportunity. Under 400 words.' },
  { id:18, category:'research', isPro:false, uses:41, title:'Literature synthesis', body:'Review the following sources on [topic] and produce a structured summary: [paste sources]. Format: 1) Main themes, 2) Points of agreement, 3) Contradictions or gaps, 4) Most important insight for [use case].' },
  { id:19, category:'research', isPro:true, uses:36, title:'Expert interview guide', body:'Create an interview guide for a 45-minute conversation with a [role] at [type of organization] about [topic]. Include: 5 open-ended questions, 3 follow-up probes per question, and one closing question about future trends.' },
  { id:20, category:'research', isPro:true, uses:28, title:'Market sizing approach', body:'Outline a market sizing approach for [market]. Use both top-down (TAM/SAM/SOM) and bottom-up methods. State key assumptions for each. Identify the 2–3 variables that most affect the estimate.' },
  { id:21, category:'strategy', isPro:false, uses:56, title:'Strategic options generator', body:'Generate 4–5 distinct strategic options for [organization] facing [challenge]. For each: name it, describe it in 2 sentences, list the main risk, and rate it on feasibility (1–5) and impact (1–5).' },
  { id:22, category:'strategy', isPro:true, uses:49, title:'Prioritization framework', body:'Help me prioritize the following initiatives: [list initiatives]. Evaluate each on: strategic fit, effort required, speed to value, and risk. Output as a 2x2 priority matrix (impact vs. effort) with recommended sequence.' },
  { id:23, category:'strategy', isPro:true, uses:44, title:'OKR drafter', body:'Draft OKRs for [team or department] for [time period]. Objective: [objective]. Write 3–4 measurable key results. Each KR should be specific, time-bound, ambitious but achievable, and clearly owned.' },
  { id:24, category:'strategy', isPro:true, uses:62, title:'Business case builder', body:'Build a concise business case for [initiative] at [organization]. Cover: problem statement, proposed solution, costs, expected benefits, risks, and recommended next steps. Audience: [decision-maker]. Length: 400 words.' },
  { id:25, category:'data', isPro:false, uses:47, title:'Dashboard KPI brief', body:'Define the key metrics for a dashboard tracking [business goal] at [type of organization]. For each metric: name, definition, data source, target, and why it matters. Include one leading and one lagging indicator.' },
  { id:26, category:'data', isPro:false, uses:38, title:'Data story builder', body:'I have data showing [finding]. Help me build a data story for [audience]. Structure: 1) The setup (context), 2) The tension (what the data reveals), 3) The resolution (recommended action). Use one analogy.' },
  { id:27, category:'data', isPro:true, uses:29, title:'Anomaly explainer', body:'I observed the following anomaly in my data: [describe anomaly]. Generate 5 hypotheses ranging from mundane (data error) to significant (real business change). Rate each likelihood 1–5 and suggest first investigation steps.' },
  { id:28, category:'data', isPro:true, uses:22, title:'Survey design assistant', body:'Design a survey to measure [what you want to measure] among [target respondents]. Include: 8–10 questions mixing Likert scale, multiple choice, and one open-ended. Avoid leading questions. Include a screening question.' },
  { id:29, category:'email', isPro:false, uses:103, title:'Post-meeting follow-up', body:'Write a professional follow-up email after a meeting with [client name] at [company]. Points discussed: [points]. Next steps agreed: [next steps]. Tone: warm but concise. End with a clear call to action and deadline.' },
  { id:30, category:'email', isPro:false, uses:58, title:'Difficult message drafter', body:'Help me write [email type] to [recipient] about [situation]. Tone: [tone]. Goals: be honest, maintain the relationship, and suggest a clear path forward.' },
  { id:31, category:'comms', isPro:true, uses:34, title:'Announcement writer', body:'Write an internal announcement for [organization] about [change or initiative]. Audience: [audience]. Cover: what\'s changing, why, timeline, what people need to do, and who to contact. Tone: [tone].' },
  { id:32, category:'comms', isPro:true, uses:41, title:'Talking points builder', body:'Build talking points for [speaker] to address [topic] with [audience]. Format: 3–5 main points, each with: one sentence summary, 2 supporting facts or examples, and a transition to the next point.' },
]

export function extractVars(body: string): string[] {
  const matches = Array.from(body.matchAll(/\[([^\]]+)\]/g))
  return Array.from(new Set(matches.map(m => m[1])))
}
